services:
  zco_search.event_listener:
    class: Zco\Bundle\SearchBundle\EventListener\EventListener
    arguments: ['@router']
    tags:
      - { name: kernel.event_subscriber }

  zco_search.search_engine:
    class: Zco\Bundle\SearchBundle\Search\Sphinx\SphinxSearchEngine
    arguments: ['%sphinx_host%', '%sphinx_port%']

  zco_search.search_service:
      class: Zco\Bundle\SearchBundle\Search\SearchService
      arguments: ['@zco_search.search_engine']