<?php

/**
 * BaseAide
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categorie_id
 * @property string $titre
 * @property string $icone
 * @property string $contenu
 * @property boolean $racine
 * @property integer $ordre
 * @property Categorie $Categorie
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAide extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_aide');
        $this->hasColumn('categorie_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('titre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('icone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('racine', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('ordre', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'date',
             ),
             'updated' => 
             array(
              'name' => 'date_edition',
             ),
             ));
        $this->actAs($timestampable0);
    }
}