<?php

/**
 * BaseQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categorie_id
 * @property integer $utilisateur_id
 * @property string $nom
 * @property string $description
 * @property enum $difficulte
 * @property timestamp $date
 * @property integer $aleatoire
 * @property boolean $visible
 * @property Categorie $Categorie
 * @property Utilisateur $Utilisateur
 * @property Doctrine_Collection $Scores
 * @property Doctrine_Collection $QuizQuestion
 * @property Doctrine_Collection $Recrutement
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseQuiz extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_quiz');
        $this->hasColumn('categorie_id', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('difficulte', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Facile',
              1 => 'Moyen',
              2 => 'Difficile',
             ),
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('aleatoire', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'cat_id'));

        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasMany('QuizScore as Scores', array(
             'local' => 'id',
             'foreign' => 'quiz_id'));

        $this->hasMany('QuizQuestion', array(
             'local' => 'id',
             'foreign' => 'quiz_id'));

        $this->hasMany('Recrutement', array(
             'local' => 'id',
             'foreign' => 'recrutement_id_quiz'));
    }
}