<?php

/**
 * zCorrecteurs.fr est le logiciel qui fait fonctionner www.zcorrecteurs.fr
 *
 * Copyright (C) 2012-2019 Corrigraphie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Quiz
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author vincent1870 <vincent@zcorrecteurs.fr>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Quiz extends BaseQuiz
{
    const LEVELS = ['Facile', 'Moyen', 'Difficile'];

    public function __toString()
    {
        return $this['nom'];
    }

    public function getNumericLevel()
    {
        return array_flip(self::LEVELS)[$this['difficulte']];
    }

    /**
     * Calcule le score à un quiz.
     * @param Doctrine_Collection $questions Les questions.
     * @return integer                                La note obtenue.
     */
    public function Soumettre(\Doctrine_Collection $questions)
    {
        //Calcul du score.
        $score = 0;
        foreach ($questions as $question) {
            if (isset($_POST['rep' . $question['id']])) {
                if ($_POST['rep' . $question['id']] != 0 && $_POST['rep' . $question['id']] == $question['reponse_juste']) {
                    $score++;
                }
            }
        }
        $note = (int)round($score / count($questions) * 20);

        $score = new QuizScore;
        $score['utilisateur_id'] = $_SESSION['id'] > 0 ? $_SESSION['id'] : null;
        $score['date'] = date('Y-m-d H:i:s');
        $score['quiz_id'] = $this['id'];
        $score['note'] = $note;
        $score->save();

        return $note;
    }
}
