pipeline:
  publish:
    image: plugins/docker
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    repo: zcorrecteurs/monolith-www
    tags: [latest, $$COMMIT]
    when:
      branch: master
      event: push
