<?php

/**
 * BaseDictee_Participation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dictee_id
 * @property integer $utilisateur_id
 * @property timestamp $date
 * @property integer $fautes
 * @property integer $note
 * @property Dictee $Dictee
 * @property Utilisateur $Utilisateur
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDictee_Participation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_dictees_participations');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('dictee_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => '11',
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('fautes', 'integer', 3, array(
             'type' => 'integer',
             'length' => '3',
             ));
        $this->hasColumn('note', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dictee', array(
             'local' => 'dictee_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));
    }
}