<?php

/**
 * BaseQuizQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quiz_id
 * @property integer $utilisateur_id
 * @property timestamp $date
 * @property string $question
 * @property string $reponse1
 * @property string $reponse2
 * @property string $reponse3
 * @property string $reponse4
 * @property integer $reponse_juste
 * @property string $explication
 * @property Quiz $Quiz
 * @property Utilisateur $Utilisateur
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseQuizQuestion extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_quiz_questions');
        $this->hasColumn('quiz_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('question', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('reponse1', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('reponse2', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('reponse3', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('reponse4', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('reponse_juste', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('explication', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quiz', array(
             'local' => 'quiz_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));
    }
}