inscription:
    credentials:  [stats_inscription]
blog_flux:
    credentials:  [stats_blog_flux]
developpement:
    credentials:  [stats_developpement]
geolocalisation:
    credentials:  [stats_geolocalisation]
graphique_ages:
    credentials:  [voir_stats_ages]
alexa:
    credentials:  [voir_stats_generales]
