groups:
    general: Configuration générale
    membres: Configuration des membres
    quiz: Configuration du quiz
constants:
    GROUPE_ADMINISTRATEURS:
        desc: ID du groupe des administrateurs
        group: membres
        type: integer
        value: 5
    GROUPE_ANCIENS:
        desc: ID du groupe des anciens
        group: membres
        type: integer
        value: 36
    GROUPE_DEFAUT:
        desc: ID du groupe par défaut
        group: membres
        type: integer
        value: 1
    GROUPE_VISITEURS:
        desc: ID du groupe des visiteurs
        group: membres
        type: integer
        value: 7