_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

zco_vitesse:
    resource: "@ZcoCoreBundle/Resources/config/routing_dev.yml"

_main:
    resource: routing.yml