zco_user_api_searchUsername:
    path:   /chercher-pseudo
    defaults:  { _controller: ZcoUserBundle:Api:searchUsername }
    options:   { expose: true }

zco_user_api_validateUsername:
    path:   /valider-pseudo
    defaults:  { _controller: ZcoUserBundle:Api:validateUsername }
    options:   { expose: true }

zco_user_api_saveZform:
    path:   /save-zform
    defaults:  { _controller: ZcoUserBundle:Api:saveZform }
    options:   { expose: true }