zco_user_ips_index:
  path:   /ips
  defaults:  { _controller: ZcoUserBundle:Ips:index }

zco_user_ips_ban:
  path:   /ips/bannir
  defaults:  { _controller: ZcoUserBundle:Ips:ban }

zco_user_ips_locate:
  path:   /ips/localiser
  defaults:  { _controller: ZcoUserBundle:Ips:locate }