services:
    zco_recrutement.event_listener:
        class: Zco\Bundle\RecrutementBundle\EventListener\EventListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    zco.admin_task.applications:
        class: Zco\Bundle\RecrutementBundle\Admin\ApplicationsPendingTask
        tags:
        - { name: zco.admin_task }