<?php

/**
 * BaseBlogTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tag
 * @property integer $id_blog
 * @property Tag $Tag
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBlogTag extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_blog_tags');
        $this->hasColumn('id_tag', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('id_blog', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tag', array(
             'local' => 'id_tag',
             'foreign' => 'tag_id'));
    }
}