<?php

/**
 * BaseBlogAuteur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $auteur_id_utilisateur
 * @property integer $auteur_id_billet
 * @property integer $status
 * @property timestamp $date
 * @property Utilisateur $User
 * @property Blog $Article
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBlogAuteur extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_blog_auteurs');
        $this->hasColumn('auteur_id_utilisateur', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('auteur_id_billet', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('auteur_statut as status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('auteur_date as date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'auteur_id_utilisateur',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('Blog as Article', array(
             'local' => 'auteur_id_billet',
             'foreign' => 'blog_id'));
    }
}