#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

umask(0000);
set_time_limit(0);

define('BASEPATH', realpath(__DIR__ . '/..'));
define('APP_PATH', BASEPATH . '/app');

/** @var \Composer\Autoload\ClassLoader $loader */
$loader = require __DIR__.'/autoload.php';


$env = getenv('ENVIRONMENT') ?: 'prod';
$debug = 'true' === getenv('DEBUG') && 'prod' !== $env;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), $env);
$debug = $debug && !$input->hasParameterOption(array('--no-debug', ''));
if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run();