<?php

/**
 * BaseSondageQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sondage_id
 * @property string $nom
 * @property integer $nb_votes
 * @property integer $nb_blanc
 * @property integer $ordre
 * @property boolean $libre
 * @property integer $nb_min_choix
 * @property integer $nb_max_choix
 * @property boolean $obligatoire
 * @property boolean $resultats_publics
 * @property Sondage $Sondage
 * @property Doctrine_Collection $Reponses
 * @property Doctrine_Collection $SondageReponse
 * @property Doctrine_Collection $Votes
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSondageQuestion extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_sondages_questions');
        $this->hasColumn('sondage_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('nb_votes', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '11',
             ));
        $this->hasColumn('nb_blanc', 'integer', 11, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '11',
             ));
        $this->hasColumn('ordre', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('libre', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('nb_min_choix', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '4',
             ));
        $this->hasColumn('nb_max_choix', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '4',
             ));
        $this->hasColumn('obligatoire', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('resultats_publics', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sondage', array(
             'local' => 'sondage_id',
             'foreign' => 'id'));

        $this->hasMany('SondageReponse as Reponses', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('SondageReponse', array(
             'local' => 'id',
             'foreign' => 'question_suivante_id'));

        $this->hasMany('SondageVote as Votes', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}