zco_file_api_save:
    path:   /sauvegarder/{id}
    defaults:  { _controller: ZcoFileBundle:Api:save, _format: json }
    options:   { expose: true }
    methods:   [POST]
    requirements:
        id: \d+

zco_file_api_edit:
    path:   /modifier/{id}
    defaults:  { _controller: ZcoFileBundle:Api:edit, _format: json }
    options:   { expose: true }
    methods:   [POST]
    requirements:
        id: \d+

zco_file_api_delete:
    path:   /supprimer/{id}
    defaults:  { _controller: ZcoFileBundle:Api:delete, _format: json }
    options:   { expose: true }
    requirements:
        id: \d+

zco_file_api_search:
    path:   /recherche/{folder}/{entities}
    defaults:  { _controller: ZcoFileBundle:Api:search, _format: json, entities: '' }
    options:   { expose: true }
    methods:   [POST]
    requirements:
        folder: \d+

zco_file_api_usage:
    path:   /usage
    defaults:  { _controller: ZcoFileBundle:Api:usage, _format: json }
    options:   { expose: true }
