zco_file_index:
    path:   /
    defaults:  { _controller: ZcoFileBundle:Default:index }
    options:   { expose: true }

zco_file_upload:
    path:   /upload
    defaults:  { _controller: ZcoFileBundle:Default:upload }
    options:   { expose: true }

zco_file_folder:
    path:   /dossier/{id}/{entities}
    defaults:  { _controller: ZcoFileBundle:Default:folder, id: 1, entities: '' }
    requirements:
        id: \d+

zco_file_file:
    path:   /fichier/{id}
    defaults:  { _controller: ZcoFileBundle:Default:file }
    options:   { expose: true }
    requirements:
        id: \d+