<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $utilisateur_id
 * @property string $nom
 * @property string $couleur
 * @property boolean $moderation
 * @property Utilisateur $Utilisateur
 * @property Doctrine_Collection $Citations
 * @property Doctrine_Collection $BlogTag
 * @property Doctrine_Collection $DicteeTag
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTag extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_tags');
        $this->hasColumn('utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '11',
             ));
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('couleur', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('moderation', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasMany('Citation as Citations', array(
             'refClass' => 'TagCitation',
             'local' => 'tag_id',
             'foreign' => 'citation_id'));

        $this->hasMany('BlogTag', array(
             'local' => 'tag_id',
             'foreign' => 'id_tag'));

        $this->hasMany('DicteeTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}