services:
    zco_core.cache.file:
        class: Zco\Bundle\CoreBundle\Cache\FileCache
        arguments: [%kernel.cache_dir%/zco_core_cache, 600, @?logger]
    
    zco_core.cache.memcache:
        class: Zco\Bundle\CoreBundle\Cache\MemcacheCache
        arguments: [600, @?logger]
    
    zco_core.cache.memory:
        class: Zco\Bundle\CoreBundle\Cache\MemoryCache
        arguments: [600, @?logger]