services:
    memcached:
        class: Memcached
        calls:
        - [addServer, ["memcached", 11211]]

    zco_core.cache.file:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: [%kernel.cache_dir%/zco_core_cache]

    zco_core.cache.memcache:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
        - [setMemcached, [@memcached]]
        - [setNamespace, 'cache']
    
    zco_core.cache.memory:
        class: Doctrine\Common\Cache\ArrayCache
