<?php

/**
 * BaseDroit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $droit_id
 * @property integer $droit_id_categorie
 * @property string $droit_nom
 * @property string $droit_description
 * @property boolean $droit_choix_categorie
 * @property boolean $droit_choix_binaire
 * @property string $droit_description_longue
 * @property Categorie $Categorie
 * @property Doctrine_Collection $GroupeDroit
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDroit extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_droits');
        $this->hasColumn('droit_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('droit_id_categorie', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('droit_nom', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('droit_description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('droit_choix_categorie', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('droit_choix_binaire', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('droit_description_longue', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorie', array(
             'local' => 'droit_id_categorie',
             'foreign' => 'cat_id'));

        $this->hasMany('GroupeDroit', array(
             'local' => 'droit_id',
             'foreign' => 'gd_id_droit'));
    }
}