<?php

/**
 * BaseGroupeDroit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gd_id_droit
 * @property integer $gd_id_groupe
 * @property integer $gd_id_categorie
 * @property integer $gd_valeur
 * @property Groupe $Groupe
 * @property Droit $Droit
 * @property Categorie $Categorie
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGroupeDroit extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_groupes_droits');
        $this->hasColumn('gd_id_droit', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('gd_id_groupe', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('gd_id_categorie', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('gd_valeur', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Groupe', array(
             'local' => 'gd_id_groupe',
             'foreign' => 'groupe_id'));

        $this->hasOne('Droit', array(
             'local' => 'gd_id_droit',
             'foreign' => 'droit_id'));

        $this->hasOne('Categorie', array(
             'local' => 'gd_id_categorie',
             'foreign' => 'cat_id'));
    }
}