zco_twitter_index:
    path:   /
    defaults:  { _controller: ZcoTwitterBundle:Default:index, page: 1 }

zco_twitter_indexWithPage:
    path:   /{page}
    defaults:  { _controller: ZcoTwitterBundle:Default:index, page: 1 }
    requirements:
        page: \d+

zco_twitter_accounts:
    path:   /comptes
    defaults:  { _controller: ZcoTwitterBundle:Default:accounts }

zco_twitter_addAccount:
    path:   /comptes/nouveau
    defaults:  { _controller: ZcoTwitterBundle:Default:addAccount }

zco_twitter_deleteAccount:
    path:   /comptes/supprimer/{id}
    defaults:  { _controller: ZcoTwitterBundle:Default:deleteAccount }
    requirements:
        id: \d+

zco_twitter_newTweet:
    path:   /nouveau-tweet/{mention}
    defaults:  { _controller: ZcoTwitterBundle:Default:newTweet, mention: ~ }
    requirements:
        id: \d+

zco_twitter_mentions:
    path:   /mentions/{page}
    defaults:  { _controller: ZcoTwitterBundle:Default:mentions, page: 1 }
    requirements:
        page: \d+