<?php

/**
 * BaseRecrutementAvis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $utilisateur_id
 * @property integer $candidature_id
 * @property integer $type
 * @property Utilisateur $Utilisateur
 * @property RecrutementCandidature $Candidature
 * @property RecrutementCandidature $RecrutementCandidature
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRecrutementAvis extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_recrutements_avis');
        $this->hasColumn('utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('candidature_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('type', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('RecrutementCandidature as Candidature', array(
             'local' => 'candidature_id',
             'foreign' => 'id'));

        $this->hasOne('RecrutementCandidature', array(
             'local' => 'candidature_id',
             'foreign' => 'candidature_id'));
    }
}