<?php

/**
 * BaseRecrutementLuNonLu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $candidature_id
 * @property integer $utilisateur_id
 * @property integer $commentaire_id
 * @property boolean $participe
 * @property Utilisateur $Utilisateur
 * @property RecrutementCandidature $Candidature
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRecrutementLuNonLu extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_recrutements_lunonlu');
        $this->hasColumn('lunonlu_candidature_id as candidature_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('lunonlu_utilisateur_id as utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('lunonlu_commentaire_id as commentaire_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lunonlu_participe as participe', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'lunonlu_utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('RecrutementCandidature as Candidature', array(
             'local' => 'lunonlu_candidature_id',
             'foreign' => 'candidature_id'));
    }
}