<?php

/**
 * BaseRecrutementCommentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $candidature_id
 * @property integer $utilisateur_id
 * @property string $texte
 * @property Utilisateur $Utilisateur
 * @property RecrutementCandidature $Candidature
 * @property RecrutementCandidature $RecrutementCandidature
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRecrutementCommentaire extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_recrutements_commentaires');
        $this->hasColumn('commentaire_id as id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('commentaire_candidature_id as candidature_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('commentaire_utilisateur_id as utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('commentaire_texte as texte', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('RecrutementCandidature as Candidature', array(
             'local' => 'candidature_id',
             'foreign' => 'id'));

        $this->hasOne('RecrutementCandidature', array(
             'local' => 'candidature_id',
             'foreign' => 'candidature_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'commentaire_date as date',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}