<?php

/**
 * BaseUserPunishment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $admin_id
 * @property integer $from_group_id
 * @property integer $to_group_id
 * @property timestamp $date
 * @property integer $duration
 * @property integer $remaining_duration
 * @property string $link
 * @property string $reason
 * @property string $admin_reason
 * @property boolean $finished
 * @property Utilisateur $User
 * @property Utilisateur $Admin
 * @property Groupe $Group
 * @property Groupe $OriginalGroup
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserPunishment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_sanctions');
        $this->hasColumn('sanction_id as id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sanction_id_utilisateur as user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sanction_id_admin as admin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sanction_id_groupe_origine as from_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sanction_id_groupe_sanction as to_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sanction_date as date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('sanction_duree as duration', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sanction_duree_restante as remaining_duration', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sanction_litige as link', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('sanction_raison as reason', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('sanction_raison_admin as admin_reason', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('sanction_finie as finished', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'user_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('Utilisateur as Admin', array(
             'local' => 'admin_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('Groupe as Group', array(
             'local' => 'to_group_id',
             'foreign' => 'groupe_id'));

        $this->hasOne('Groupe as OriginalGroup', array(
             'local' => 'from_group_id',
             'foreign' => 'groupe_id'));
    }
}