<?php

/**
 * BaseUserNewUsername
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $admin_id
 * @property string $old_username
 * @property string $new_username
 * @property string $reason
 * @property string $response
 * @property integer $status
 * @property Utilisateur $User
 * @property Utilisateur $Admin
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserNewUsername extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_changements_pseudos');
        $this->hasColumn('changement_id as id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('changement_id_utilisateur as user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('changement_id_admin as admin_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('changement_ancien_pseudo as old_username', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('changement_nouveau_pseudo as new_username', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('changement_raison as reason', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('changement_reponse as response', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('changement_etat as status', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur as Admin', array(
             'local' => 'admin_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'changement_date',
             ),
             'updated' => 
             array(
              'name' => 'changement_date_reponse',
             ),
             ));
        $this->actAs($timestampable0);
    }
}