<?php

/**
 * BaseTentative
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ip
 * @property boolean $blocage
 * @property integer $user
 * @property Utilisateur $Utilisateur
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTentative extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_tentatives');
        $this->hasColumn('ip', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('blocage', 'boolean', null, array(
             'type' => 'boolean',
             'default' => '0',
             ));
        $this->hasColumn('user', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'user',
             'foreign' => 'utilisateur_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'date',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}