<?php

/**
 * BaseUtilisateurIp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ip_id_utilisateur
 * @property integer $ip_ip
 * @property timestamp $date_debut
 * @property timestamp $date_last
 * @property string $localisation
 * @property integer $proxy
 * @property Utilisateur $Utilisateur
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUtilisateurIp extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_utilisateurs_ips');
        $this->hasColumn('ip_id_utilisateur', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('ip_ip', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('ip_date_debut as date_debut', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('ip_date_last as date_last', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('ip_localisation as localisation', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('ip_proxy as proxy', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'ip_id_utilisateur',
             'foreign' => 'utilisateur_id'));
    }
}