<?php

/**
 * BaseZformBackup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property timestamp $date
 * @property string $content
 * @property string $url
 * @property Utilisateur $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseZformBackup extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_sauvegardes_zform');
        $this->hasColumn('sauvegarde_id as id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sauvegarde_id_utilisateur as user_id', 'integer', 3, array(
             'type' => 'integer',
             'length' => '3',
             ));
        $this->hasColumn('sauvegarde_date as date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('sauvegarde_texte as content', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('sauvegarde_url as url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}