<?php

/**
 * BaseUserPreference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property boolean $display_admin_bar
 * @property boolean $beta_tests
 * @property boolean $email_on_mp
 * @property integer $time_difference
 * @property Utilisateur $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserPreference extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_utilisateurs_preferences');
        $this->hasColumn('preference_id_utilisateur as user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('preference_afficher_admin_rapide as display_admin_bar', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('preference_beta_tests as beta_tests', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('preference_activer_email_mp as email_on_mp', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('preference_decalage as time_difference', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}