<?php

/**
 * BaseBannedEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $utilisateur_id
 * @property string $mail
 * @property string $raison
 * @property Utilisateur $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBannedEmail extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_mails_bannis');
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('raison', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));
    }
}