<?php

/**
 * BaseUserWarning
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $admin_id
 * @property integer $percentage
 * @property string $link
 * @property timestamp $date
 * @property string $reason
 * @property string $admin_reason
 * @property Utilisateur $User
 * @property Utilisateur $Admin
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserWarning extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_avertissements');
        $this->hasColumn('averto_id as id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('averto_id_utilisateur as user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('averto_id_admin as admin_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('averto_pourcentage as percentage', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('averto_litige as link', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('averto_date as date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('averto_raison as reason', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('averto_raison_admin as admin_reason', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur as User', array(
             'local' => 'user_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('Utilisateur as Admin', array(
             'local' => 'admin_id',
             'foreign' => 'utilisateur_id'));
    }
}