all:
    login_required:  on
    credentials:     [connecte]
nouveau_mp_semi_auto:
    credentials:   [connecte, mp_envoyer_auto]
marquer_alertes_resolues:
    credentials:   [connecte, mp_alertes]
alertes:
    credentials:   [connecte, mp_alertes]
alertes:
    credentials:   [connecte, mp_signaler]
