services:
    zco_mp.event_listener:
        class: Zco\Bundle\MpBundle\EventListener\EventListener
        arguments: ["@zco_core.cache", "@zco_admin.manager"]
        tags:
            - { name: kernel.event_subscriber }