<?php

/**
 * BaseAnnonce
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $utilisateur_id
 * @property string $nom
 * @property timestamp $date_debut
 * @property timestamp $date_fin
 * @property boolean $actif
 * @property integer $poids
 * @property string $contenu
 * @property integer $nb_clics
 * @property integer $nb_affichages
 * @property integer $nb_fermetures
 * @property boolean $aff_pays_inconnu
 * @property string $url_destination
 * @property Utilisateur $Utilisateur
 * @property Doctrine_Collection $Pays
 * @property Doctrine_Collection $Groupes
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $Domaines
 * @property Doctrine_Collection $AnnonceCategorie
 * @property Doctrine_Collection $AnnoncePays
 * @property Doctrine_Collection $AnnonceGroupe
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAnnonce extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_annonces');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('date_debut', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('date_fin', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('actif', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => '1',
             ));
        $this->hasColumn('poids', 'integer', null, array(
             'type' => 'integer',
             'default' => 100,
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('nb_clics', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('nb_affichages', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('nb_fermetures', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('aff_pays_inconnu', 'boolean', null, array(
             'type' => 'boolean',
             'default' => '1',
             ));
        $this->hasColumn('url_destination', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasMany('Pays', array(
             'refClass' => 'AnnoncePays',
             'local' => 'annonce_id',
             'foreign' => 'pays_id'));

        $this->hasMany('Groupe as Groupes', array(
             'refClass' => 'AnnonceGroupe',
             'local' => 'annonce_id',
             'foreign' => 'groupe_id'));

        $this->hasMany('Categorie as Categories', array(
             'refClass' => 'AnnonceCategorie',
             'local' => 'annonce_id',
             'foreign' => 'categorie_id'));

        $this->hasMany('AnnonceDomaine as Domaines', array(
             'local' => 'id',
             'foreign' => 'annonce_id'));

        $this->hasMany('AnnonceCategorie', array(
             'local' => 'id',
             'foreign' => 'annonce_id'));

        $this->hasMany('AnnoncePays', array(
             'local' => 'id',
             'foreign' => 'annonce_id'));

        $this->hasMany('AnnonceGroupe', array(
             'local' => 'id',
             'foreign' => 'annonce_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'date',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}