<?php

/**
 * BaseAnnonceCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $annonce_id
 * @property integer $categorie_id
 * @property Annonce $Annonce
 * @property Categorie $Categorie
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAnnonceCategorie extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_annonces_categories');
        $this->hasColumn('annonce_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('categorie_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Annonce', array(
             'local' => 'annonce_id',
             'foreign' => 'id'));

        $this->hasOne('Categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'cat_id'));
    }
}