<?php

/**
 * BaseTrackerTicketFlag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lunonlu_id_utilisateur
 * @property integer $lunonlu_id_ticket
 * @property integer $lunonlu_id_version
 * @property integer $lunonlu_suivi
 * @property integer $lunonlu_suivi_envoye
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTrackerTicketFlag extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_tracker_tickets_flags');
        $this->hasColumn('lunonlu_id_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('lunonlu_id_ticket', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('lunonlu_id_version', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('lunonlu_suivi', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('lunonlu_suivi_envoye', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}