services:
    zco_forum.event_listener:
        class: Zco\Bundle\ForumBundle\EventListener\EventListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    zco.admin_task.forum_alerts:
        class: Zco\Bundle\ForumBundle\Admin\ForumAlertsPendingTask
        tags:
        - { name: zco.admin_task }