zco_blog_index:
  path:   /blog
  defaults:  { _controller: ZcoBlogBundle:Default:index }

zco_blog_feed:
  path:   /blog/feed.xml
  defaults:  { _controller: ZcoBlogBundle:Feed:index }

zco_blog_show:
  path:   /blog/{id}/{slug}
  defaults:  { _controller: ZcoBlogBundle:Default:show }
  requirements:
    id: \d+

zco_blog_manage:
  path:   /blog/gestion/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:manage }
  requirements:
    id: \d+

zco_blog_editAuthor:
  path:   /blog/auteur/{id}/{authorId}/modifier
  defaults:  { _controller: ZcoBlogBundle:Default:editAuthor }
  requirements:
    id: \d+
    authorId: \d+

zco_blog_deleteAuthor:
  path:   /blog/auteur/{id}/{authorId}/supprimer
  defaults:  { _controller: ZcoBlogBundle:Default:deleteAuthor }
  requirements:
    id: \d+
    authorId: \d+

zco_blog_publish:
  path:   /blog/valider/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:publish }
  requirements:
    id: \d+

zco_blog_unpublish:
  path:   /blog/devalider/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:unpublish }
  requirements:
    id: \d+

zco_blog_history:
  path:   /blog/versions/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:history }
  requirements:
    id: \d+

zco_blog_edit:
  path:   /blog/modifier/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:edit }
  requirements:
    id: \d+

zco_blog_delete:
  path:   /blog/supprimer/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:delete }
  requirements:
    id: \d+

zco_blog_compare:
  path:   /blog/comparaison/{from}/{to}
  defaults:  { _controller: ZcoBlogBundle:Default:compare }
  requirements:
    from: \d+
    to: \d+

zco_blog_new:
  path:   /blog/nouveau
  defaults:  { _controller: ZcoBlogBundle:Default:new }

zco_blog_mine:
  path:   /blog/mes-billets
  defaults:  { _controller: ZcoBlogBundle:Default:mine }

zco_blog_newComment:
  path:   /blog/commenter/{id}
  defaults:  { _controller: ZcoBlogBundle:Default:newComment }
  requirements:
    id: \d+

zco_blog_editComment:
  path:   /blog/commentaire/{id}/modifier
  defaults:  { _controller: ZcoBlogBundle:Default:editComment }
  requirements:
    id: \d+

zco_blog_deleteComment:
  path:   /blog/commentaire/{id}/supprimer
  defaults:  { _controller: ZcoBlogBundle:Default:deleteComment }
  requirements:
    id: \d+