zco_forum_index:
  path:   /forum
  defaults:  { _controller: ZcoForumBundle:Default:index }

zco_forum_show:
  path:   /forum/categorie/{id}/{slug}
  defaults:  { _controller: ZcoForumBundle:Default:showForum }
  requirements:
    id: \d+

zco_forum_showTopic:
  path:   /forum/sujet/{id}/{slug}
  defaults:  { _controller: ZcoForumBundle:Topic:show }
  requirements:
    id: \d+

zco_forum_newTopic:
  path:   /forum/nouveau-sujet/{id}
  defaults:  { _controller: ZcoForumBundle:Topic:new }
  requirements:
    id: \d+

zco_forum_trash:
  path:   /forum/corbeille/{id}
  defaults:  { _controller: ZcoForumBundle:Topic:trash }
  requirements:
    id: \d+

zco_forum_markHelped:
  path:   /forum/aide/{id}
  defaults:  { _controller: ZcoForumBundle:Message:markHelped }
  requirements:
    id: \d+

zco_forum_markSolved:
  path:   /forum/resolu/{id}
  defaults:  { _controller: ZcoForumBundle:Topic:markSolved }
  requirements:
    id: \d+

zco_forum_markPinned:
  path:   /forum/annonce/{id}
  defaults:  { _controller: ZcoForumBundle:Topic:markPinned }
  requirements:
    id: \d+

zco_forum_markClosed:
  path:   /forum/ferme/{id}
  defaults:  { _controller: ZcoForumBundle:Topic:markClosed }
  requirements:
    id: \d+

zco_forum_delete:
  path:   /forum/supprimer/{id}
  defaults:  { _controller: ZcoForumBundle:Topic:delete }
  requirements:
    id: \d+

zco_forum_reply:
  path:   /forum/repondre/{id}
  defaults:  { _controller: ZcoForumBundle:Message:new }
  methods: [POST]
  requirements:
    id: \d+

zco_forum_move:
  path:   /forum/deplacer/{id}
  defaults:  { _controller: ZcoForumBundle:Default:move }
  methods: [POST]
  requirements:
    id: \d+

zco_forum_edit:
  path:   /forum/modifier/{id}
  defaults:  { _controller: ZcoForumBundle:Message:edit }
  requirements:
    id: \d+

zco_forum_deleteMessage:
  path:   /forum/supprimer-message/{id}
  defaults:  { _controller: ZcoForumBundle:Message:delete }
  requirements:
    id: \d+