zco_forum_index:
  path:   /forum
  defaults:  { _controller: ZcoContentBundle:Forum:index }

zco_forum_show:
  path:   /forum/categorie/{id}/{slug}
  defaults:  { _controller: ZcoContentBundle:Forum:showForum }
  requirements:
    id: \d+

zco_topic_show:
  path:   /forum/sujet/{id}/{slug}
  defaults:  { _controller: ZcoContentBundle:Topic:show }
  requirements:
    id: \d+

zco_topic_new:
  path:   /forum/nouveau-sujet/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:new }
  requirements:
    id: \d+

zco_topic_trash:
  path:   /forum/corbeille/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:trash }
  requirements:
    id: \d+

zco_message_markHelped:
  path:   /forum/aide/{id}
  defaults:  { _controller: ZcoContentBundle:Message:markHelped }
  requirements:
    id: \d+

zco_topic_markSolved:
  path:   /forum/resolu/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:markSolved }
  requirements:
    id: \d+

zco_topic_markPinned:
  path:   /forum/annonce/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:markPinned }
  requirements:
    id: \d+

zco_topic_markClosed:
  path:   /forum/ferme/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:markClosed }
  requirements:
    id: \d+

zco_topic_delete:
  path:   /forum/supprimer/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:delete }
  requirements:
    id: \d+

zco_message_new:
  path:   /forum/repondre/{id}
  defaults:  { _controller: ZcoContentBundle:Message:new }
  methods: [POST]
  requirements:
    id: \d+

zco_topic_move:
  path:   /forum/deplacer/{id}
  defaults:  { _controller: ZcoContentBundle:Topic:move }
  methods: [POST]
  requirements:
    id: \d+

zco_message_edit:
  path:   /forum/modifier/{id}
  defaults:  { _controller: ZcoContentBundle:Message:edit }
  requirements:
    id: \d+

zco_message_delete:
  path:   /forum/supprimer-message/{id}
  defaults:  { _controller: ZcoContentBundle:Message:delete }
  requirements:
    id: \d+