zco_home:
  path:   /
  defaults:  { _controller: ZcoCoreBundle:Home:index }

zco_about_index:
  path:   /apropos
  defaults:  { _controller: ZcoCoreBundle:Static:index }

zco_about_banners:
  path:   /apropos/bannieres
  defaults:  { _controller: ZcoCoreBundle:Static:banners }

zco_about_team:
  path:   /apropos/equipe
  defaults:  { _controller: ZcoCoreBundle:Static:team }

zco_about_corrigraphie:
  path:   /apropos/association-corrigraphie
  defaults:  { _controller: ZcoCoreBundle:Static:corrigraphie }

zco_about_opensource:
  path:   /apropos/logiciel-libre
  defaults:  { _controller: ZcoCoreBundle:Static:openSource }

zco_about_contact:
  path:   /apropos/contact
  defaults:  { _controller: ZcoCoreBundle:Static:contact }

zco_donate_index:
  path:  /dons
  defaults:  { _controller: ZcoCoreBundle:Static:donate }

zco_donate_otherWays:
  path:  /dons/cheque-ou-virement
  defaults:  { _controller: ZcoCoreBundle:Static:donateOtherWays }

zco_donate_fiscalDeduction:
  path:  /dons/deduction-fiscale
  defaults:  { _controller: ZcoCoreBundle:Static:donateFiscalDeduction }

zco_donate_thanks:
  path:  /dons/merci
  defaults:  { _controller: ZcoCoreBundle:Static:donateThanks }

zco_legal_mentions:
  path:   /legal/mentions
  defaults:  { _controller: ZcoCoreBundle:Static:mentions }

zco_legal_privacy:
  path:   /legal/confidentialite
  defaults:  { _controller: ZcoCoreBundle:Static:privacy }

zco_legal_rules:
  path:   /legal/reglement
  defaults:  { _controller: ZcoCoreBundle:Static:rules }

zco_error:
  path:   /_erreur/{code}
  requirements:
    code: \d+
  defaults:  { _controller: ZcoCoreBundle:Static:error }

zco_sitemap:
  path:   /sitemap.xml
  defaults:  { _controller: ZcoCoreBundle:Default:sitemap }

zco_health:
  path:   /health
  defaults:  { _controller: ZcoCoreBundle:Default:health }

zco_robots:
  path:   /robots.txt
  defaults:  { _controller: ZcoCoreBundle:Default:robots }
