zco_stats_alexa:
  path:   /admin/stats/alexa
  defaults:  { _controller: ZcoStatsBundle:Default:alexa }

zco_stats_alexaChart:
  path:   /admin/stats/alexa.png
  defaults:  { _controller: ZcoStatsBundle:Default:alexaChart }

zco_stats_registration:
  path:   /admin/stats/inscription
  defaults:  { _controller: ZcoStatsBundle:Default:registration }

zco_stats_registrationChart:
  path:   /admin/stats/inscription.png
  defaults:  { _controller: ZcoStatsBundle:Default:registrationChart }
