mes_statistiques:
    login_required: true
statistiques:
    credentials:  [quiz_stats_generales]
statistiques_popularite:
    credentials:  [quiz_stats_generales]
gestion:
    credentials:  [quiz_ajouter]
ajouter_quiz:
    credentials:  [quiz_ajouter]
valider_quiz:
    credentials:  [quiz_ajouter]
deplacer_question:
    credentials:  [quiz_ajouter]

