<?php

/**
 * BaseDicteeTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dictee_id
 * @property integer $tag_id
 * @property Dictee $Dictee
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDicteeTag extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_dictees_tags');
        $this->hasColumn('dictee_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dictee', array(
             'local' => 'dictee_id',
             'foreign' => 'id'));
    }
}