zco_quote_index:
  path:   /citations
  defaults:  { _controller: ZcoCitationsBundle:Default:index }

zco_quote_new:
  path:   /citations/ajouter
  defaults:  { _controller: ZcoCitationsBundle:Default:new }

zco_quote_edit:
  path:   /citations/modifier/{id}
  defaults:  { _controller: ZcoCitationsBundle:Default:edit }
  requirements:
    id: \d+

zco_quote_delete:
  path:   /citations/supprimer/{id}
  defaults:  { _controller: ZcoCitationsBundle:Default:delete }
  requirements:
    id: \d+
