services:
  zco_citations.event_listener:
    class: Zco\Bundle\CitationsBundle\EventListener\EventListener
    calls:
    - [setContainer, ["@service_container"]]
    tags:
    - { name: kernel.event_subscriber }

  zco.repository.quotes:
    class: Zco\Bundle\CitationsBundle\Domain\QuoteRepository
    arguments: ['@zco_doctrine1.connection']