<?php

/**
 * BaseForumLunonlu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lunonlu_utilisateur_id
 * @property integer $lunonlu_sujet_id
 * @property integer $lunonlu_message_id
 * @property boolean $lunonlu_participe
 * @property boolean $lunonlu_favori
 * @property Utilisateur $Utilisateur
 * @property ForumSujet $Sujet
 * @property ForumMessage $Message
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseForumLunonlu extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_forum_lunonlu');
        $this->hasColumn('lunonlu_utilisateur_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('lunonlu_sujet_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('lunonlu_message_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('lunonlu_participe', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('lunonlu_favori', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'lunonlu_utilisateur_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('ForumSujet as Sujet', array(
             'local' => 'lunonlu_sujet_id',
             'foreign' => 'sujet_id'));

        $this->hasOne('ForumMessage as Message', array(
             'local' => 'lunonlu_message_id',
             'foreign' => 'message_id'));
    }
}