<?php

/**
 * BaseForumMessageAuto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $tag
 * @property string $texte
 * @property boolean $ferme
 * @property boolean $resolu
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseForumMessageAuto extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_forum_messages_autos');
        $this->hasColumn('id', 'integer', 1, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '1',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('tag', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('texte', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('ferme', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('resolu', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}