<?php

/**
 * BaseForumMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sujet_id
 * @property integer $message_edite_auteur
 * @property integer $message_auteur
 * @property string $texte
 * @property timestamp $date
 * @property timestamp $edite_date
 * @property integer $ip
 * @property boolean $help
 * @property Utilisateur $Utilisateur
 * @property Utilisateur $Editeur
 * @property ForumSujet $Sujet
 * @property Doctrine_Collection $ForumLunonlu
 * @property Doctrine_Collection $ForumSujet
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseForumMessage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_forum_messages');
        $this->hasColumn('message_id as id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('message_sujet_id as sujet_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('message_edite_auteur', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('message_auteur', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('message_texte as texte', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('message_date as date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('message_edite_date as edite_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('message_ip as ip', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('message_help as help', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'message_auteur',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('Utilisateur as Editeur', array(
             'local' => 'message_edite_auteur',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('ForumSujet as Sujet', array(
             'local' => 'sujet_id',
             'foreign' => 'sujet_id'));

        $this->hasMany('ForumLunonlu', array(
             'local' => 'message_id',
             'foreign' => 'lunonlu_message_id'));

        $this->hasMany('ForumSujet', array(
             'local' => 'message_id',
             'foreign' => 'sujet_premier_message'));
    }
}