<?php

/**
 * BaseForumSujet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $forum_id
 * @property string $titre
 * @property string $sous_titre
 * @property integer $sujet_auteur
 * @property timestamp $date
 * @property integer $sujet_premier_message
 * @property integer $sujet_dernier_message
 * @property integer $reponses
 * @property integer $sondage
 * @property boolean $annonce
 * @property boolea $ferme
 * @property boolean $resolu
 * @property boolean $corbeille
 * @property boolean $coup_coeur
 * @property Utilisateur $Utilisateur
 * @property Categorie $Categorie
 * @property ForumMessage $PremierMessage
 * @property ForumMessage $DernierMessage
 * @property ForumSondage $Sondage
 * @property Doctrine_Collection $ForumAlerte
 * @property Doctrine_Collection $ForumLunonlu
 * @property Doctrine_Collection $ForumMessage
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseForumSujet extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_forum_sujets');
        $this->hasColumn('sujet_id as id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('sujet_forum_id as forum_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('sujet_titre as titre', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('sujet_sous_titre as sous_titre', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('sujet_auteur', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('sujet_date as date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
        $this->hasColumn('sujet_premier_message', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('sujet_dernier_message', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('sujet_reponses as reponses', 'integer', 11, array(
             'type' => 'integer',
             'default' => '0',
             'length' => '11',
             ));
        $this->hasColumn('sujet_sondage as sondage', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => '11',
             ));
        $this->hasColumn('sujet_annonce as annonce', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('sujet_ferme as ferme', 'boolea', null, array(
             'type' => 'boolea',
             ));
        $this->hasColumn('sujet_resolu as resolu', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('sujet_corbeille as corbeille', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('sujet_coup_coeur as coup_coeur', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'sujet_auteur',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('Categorie', array(
             'local' => 'sujet_forum_id',
             'foreign' => 'cat_id'));

        $this->hasOne('ForumMessage as PremierMessage', array(
             'local' => 'sujet_premier_message',
             'foreign' => 'message_id'));

        $this->hasOne('ForumMessage as DernierMessage', array(
             'local' => 'sujet_dernier_message',
             'foreign' => 'message_id'));

        $this->hasOne('ForumSondage as Sondage', array(
             'local' => 'sujet_sondage',
             'foreign' => 'sondage_id'));

        $this->hasMany('ForumAlerte', array(
             'local' => 'sujet_id',
             'foreign' => 'sujet_id'));

        $this->hasMany('ForumLunonlu', array(
             'local' => 'sujet_id',
             'foreign' => 'lunonlu_sujet_id'));

        $this->hasMany('ForumMessage', array(
             'local' => 'sujet_id',
             'foreign' => 'sujet_id'));
    }
}