<?php

/**
 * BaseForumSondageChoix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $choix_id
 * @property integer $choix_sondage_id
 * @property string $choix_texte
 * @property ForumSondage $Sondage
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseForumSondageChoix extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_forum_sondages_choix');
        $this->hasColumn('choix_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('choix_sondage_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('choix_texte', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ForumSondage as Sondage', array(
             'local' => 'choix_sondage_id',
             'foreign' => 'sondage_id'));
    }
}