<?php

/**
 * BaseForumSondageVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vote_membre_id
 * @property integer $vote_sondage_id
 * @property integer $vote_choix
 * @property timestamp $vote_date
 * @property Utilisateur $Utilisateur
 * @property ForumSondage $Sondage
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseForumSondageVote extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('zcov2_forum_sondages_votes');
        $this->hasColumn('vote_membre_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('vote_sondage_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('vote_choix', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('vote_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'vote_membre_id',
             'foreign' => 'utilisateur_id'));

        $this->hasOne('ForumSondage as Sondage', array(
             'local' => 'vote_sondage_id',
             'foreign' => 'sondage_id'));
    }
}